/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Arrange: typeof import('./src/components/menu/view/arrange.vue')['default']
    EditDel: typeof import('./src/components/menu/edit/editDel.vue')['default']
    EditMenu: typeof import('./src/components/menu/edit/editMenu.vue')['default']
    Expand: typeof import('./src/components/menu/edit/expand.vue')['default']
    FontOperation: typeof import('./src/components/menu/view/fontOperation.vue')['default']
    Header: typeof import('./src/components/main/header.vue')['default']
    InsertBox: typeof import('./src/components/menu/edit/insertBox.vue')['default']
    MainEditor: typeof import('./src/components/main/mainEditor.vue')['default']
    MinderEditor: typeof import('./src/components/minderEditor.vue')['default']
    Mold: typeof import('./src/components/menu/view/mold.vue')['default']
    MoveBox: typeof import('./src/components/menu/edit/moveBox.vue')['default']
    Navigator: typeof import('./src/components/main/navigator.vue')['default']
    ProgressBox: typeof import('./src/components/menu/edit/progressBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Selection: typeof import('./src/components/menu/edit/selection.vue')['default']
    SequenceBox: typeof import('./src/components/menu/edit/sequenceBox.vue')['default']
    StyleOperation: typeof import('./src/components/menu/view/styleOperation.vue')['default']
    TagBox: typeof import('./src/components/menu/edit/tagBox.vue')['default']
    ViewMenu: typeof import('./src/components/menu/view/viewMenu.vue')['default']
  }
}
